#!/usr/bin/env bash
#displaying Best School 10 time and hi to line 9
COUNTER=0

while [ $COUNTER -lt 11 ]

do

if [ $COUNTER = 9 ]

then

echo "Hi"

else

echo "Best School"

fi

let COUNTER+=1

done
